language: java

install:
    - scripts/install-dependencies.sh
    - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - _JAVA_OPTIONS= MAVEN_SKIP_RC=true MAVEN_OPTS="-Djava.library.path=./lib" mvn test -B
